spring.application.name: api-consumer

server.port: 9000

spring:
  cloud:
    consul:
      host: consul-server
#      host: localhost
      port: 8500
      enabled: true
      discovery:
        register: false
