spring.application.name: api-consumer

server.port: 9000

spring:
  cloud:
    consul:
      enabled: false
      host: consul-server
      port: 8500
      discovery:
        register: false


# sleuth
spring.sleuth.sampler.percentage: 1

# zipkin
spring:
  zipkin:
    base-url: http://192.168.99.100:9411/
    host: 192.168.99.100
    pport: 9411

zipkin.service.port: 8080